
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: istio-system
spec:
  acme:
    email: <>@naver.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
            - "reines-test.link"
            - "*.reines-test.link"
        dns01:
          route53:
            region: ap-northeast-2
            hostedZoneID: <>

#---
#            role: arn:aws:iam::<>
#            accessKeyID: ""
#            secretAccessKeySecretRef:
#              name: cert-manager-secret
#              key: secret-token

#---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: le-crt
#  namespace: istio-system
#spec:
#  secretName: tls-secret
#  issuerRef:
#    name: letsencrypt-prod
#    kind: ClusterIssuer
#  commonName: <>.reines-test.link
#  dnsNames:
#    - <>.reines-test.link
